# Generated by Django 2.1.2 on 2018-10-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
