# Generated by Django 2.1.2 on 2018-10-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Section'),
            preserve_default=False,
        ),
    ]
