# Generated by Django 2.1.2 on 2018-11-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
