# Generated by Django 2.1.2 on 2018-11-05 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='header_photo',
        ),
        migrations.RemoveField(
            model_name='about',
            name='service_photo',
        ),
    ]
