# Generated by Django 2.1.2 on 2018-11-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20181105_0347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
