# Generated by Django 2.1.2 on 2018-10-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181031_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='subheader',
            field=models.TextField(blank=True),
        ),
    ]
