# Generated by Django 2.1.2 on 2018-11-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20181031_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='main_image',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
